var GAME_LEVELS = [
  ["                                v                                           xxxx",
   "                                                                              xx",
   "                                                                              xx",
   "                                                                              xx",
   "                                                                              xx",
   "  y                                                                           xx",
   "  x                                                                            h",
   "  x                                                                       yyyyyy",
   "  x                                                                       xxxxxx",
   "  x                 s                                                    yxxxxxx",
   "  x                                                             y!!!yy   xxxxxxx",
   "  x                 yyy                                         xxxxxx     xxxxx",
   "  x                                                                        xxxxx",
   "  x                                                                   y    xxxxx",
   "  x #        yyy                           #          yyyyyyyy          y  xxxxx",
   "  x          x                                                           s xxxxx",
   "  x          x                                                             xxxxx",
   "  x          x             yy                                       yyyyyyyxxxxx",
   "  x          x                           !yyyyyy                    xxxxxxxxxxxx",
   "  x    @     x                           !xxxxxx                    xxxxxxxxxxxx",
   "  xyyyyyyyyyyx                           !xxxxxx                    xxxxxxxxxxxx",
   "  xxxxxxxxxxxx                    yyyyy  xxxxxxx                    xxxxxxxxxxxx",
   "  xxxxxxxxxxxx                           xxxxxxx                    xxxxxxxxxxxx",
   "  xxxxxxxxxxxx                           xxxxxxx                    xxxxxxxxxxxx"],




  ["                                                                                                                  ",
   "                                             xxxxxxxxxxxxxxxxx              yyyyyyy                               ",
   "                                             x               x         yyyyy v    x                               ",
   "                              #              x               x                    x                           xxxx",
   "                  yyyy                       x               x                    x                              h",
   "                  x                          xxxxxxxxxxxxxxxxx         #          x                              h",
   "                  x          i              s                                     x                              h",
   "                  x                          yyyyyyyyyyyyyyyyy                   sx                         yyyyyy",
   "                  x                 @        x    xxxxxxxxxxxx                    x                               ",
   "                  xyyyyyyyyyyyyyyyyyyyyyyyyyyx    xxxxxxxxxxxx                    x                  i            ",
   "                                                  xxxxxxxxxxxxyyyyyyyyyyy         xxx                             ",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxx             x     #                     ",
   " =                                                xxxxxxxxxxxxxxxxxxxxxxx             x            yyyyy          ",
   "    yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy    xxxxxxxxxxx                    xxxxxx                           ",
   "    xx      v                                                                         x                           ",
   "    xx                                                                                xyyyyyyyyyyyyy              ",
   "    xx                    i         yyyyyyyyyy                                                                    ",
   "    xx                                                                                                             ",
   "    xx                #                                                                                           ",
   "xxxxxx  s                                                                                                         ",
   "h                                                                                                                 ",
   "yyyyyyyyyy                                                                                                        ",
   "                         yyyyy                                                                                    ",
   "                                               yyyyyyyyyyyyyy                                                     ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  "],



  ["                                     xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                              ",
   "                                     x!=       s                x                                              ",
   "                                     xx                         x                                              ",
   "                          x!xxxxxxxxxxx   yyy                   x                                              ",
   "                           v                                    x                                              ",
   "                              yyyyyyyyyy                        x                                              ",
   "                              x                                 x                                              ",
   "                              x                yyyy!            x                                              ",
   "         xx                   x                                 x                                              ",
   "         x!=                  x                      i          x                                              ",
   "         xx           yyyyy yyx                                 x                                              ",
   "xxxxxxxxxxx                                                     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        ",
   "                                                         #                                            x        ",
   "                  yyy                              yyyy                 i                             x        ",
   "  i          #                                                                                        x        ",
   "                                                                            =                         x        ",
   "                                                         yyyyyyyyy!!!yyyyyyyyyyyyyyyyyyyyyyyyyy       x        ",
   "                                                                                   x                  x        ",
   "   !!!!!!!!yyyyyyy                                                                 x                  x        ",
   "   xxxxxxxxxxxxxxx                                                                 x                  x        ",
   "                                                                                   x                  x        ",
   "                                                                                   x                  x        ",
   "yyyyyy                                                                             x                  x        ",
   "h                                                                                  xyyy!yyy           x        ",
   "h                                                                           x          v              x        ",
   "h                                                          s                x                         x        ",
   "yyyyyy                                                                      x                 yyyy    x        ",
   "                                                                            x               i         x        ",
   "                                                                            x                         x        ",
   "                                                          y!!y              x                         x        ",
   "                                                          yyyy                                        x        ",
   "                                                                      xxxxxxx=                        x        ",
   "            x                                                               x    #  yyyyy             x        ",
   "            x                                                               x                         x        ",
   "            x                                     yyy                       x                         x        ",
   "            x                                                               x                         x        ",
   "            x      =                  x                                     x                         x        ",
   "            x                   yyyyy x                                     x                         x        ",
   "            x                         x                                     x   yyy                   x        ",
   "            x                         x                                     x                         x        ",
   "            x          yyy            x                                     x                         x        ",
   "            x                   #     x     yyyyy                           x                         x        ",
   "            x                         x                                     xyyyyyyyyyyyyyyyyyyyyyyyyyx        ",
   "            x                         x                                                                        ",
   "            x       @                 x                                                                        ",
   "            xyyyyyyyyyyyyyyyyyyyyyyyyyx                                                                        ",
   "                                                                                                               "],


  ["                                                                                ",       
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "      x    x    xxx     xx   xx      x         x     xxxxxx    xxxx    xx       ",
   "      x    x  xx   xx   xx   xx      x         x       xx      xx xx   xx       ",
   "       x  x   xx   xx   xx   xx      x    x    x       xx      xx  xx  xx       ",
   "        xx    xx   xx   xx   xx      x    x    x       xx      xx   xx xx       ",
   "        xx    xx   xx   xx   xx      xx  xxx  xx       xx      xx    xxxx       ",
   "        xx      xxx       xxx          xx   xx       xxxxxx    xx     xxx       ",
   "                                                                                ",
   "   @                                                                            ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
